
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
  
  # Stage.
  config.vm.define "stage" do | stage |
  
	stage.vm.network :public_network, ip: "192.168.1.17"
	stage.vm.network :private_network, ip: "10.141.100.18"
	
    stage.vm.box = "ubuntu/bionic64"

    stage.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end

    stage.vm.provision "file", source: "clone.sh", destination: "clone.sh"

    stage.vm.provision :shell, inline: "apt-get update"
    
	stage.vm.provision "shell", path: "./clone.sh"
    
	stage.vm.provision :docker
    stage.vm.provision :docker_compose, yml: ["/home/vagrant/lemoras_devops/environment/stage/docker-compose.yml", 
											  "/home/vagrant/lemoras_devops/environment/stage/docker-compose.override.yml"], run:"always", rebuild: true 
  end 
  
  
    # Prod.
  config.vm.define "prod" do | prod |
	
	prod.vm.network :public_network, ip: "192.168.1.15"
	prod.vm.network :public_network, ip: "192.168.2.15"
	
    prod.vm.box = "ubuntu/bionic64"

    # Forward ports
    #prod.vm.network "forwarded_port", guest: 80, host: 8080 # run with administrator, sudo 
    
	#    test.disksize.size = '10GB'

    prod.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end

    prod.vm.provision "file", source: "clone.sh", destination: "clone.sh"

    prod.vm.provision :shell, inline: "apt-get update"
    
	prod.vm.provision "shell", path: "./clone.sh"
	
	prod.vm.provision :docker
    prod.vm.provision :docker_compose
  
  end
  
  
   # gateway.
  config.vm.define "gateway" do | gateway |
  
	gateway.vm.network :public_network, ip: "192.168.1.21", :mac => "B827EB7F61F9", route: "192.168.1.1"
	#gateway.vm.network :private_network, ip: "192.168.1.21"
	
    gateway.vm.box = "ubuntu/bionic64"

    # Forward ports
    gateway.vm.network "forwarded_port", guest: 80, host: 80 # run with administrator, sudo 
    

    gateway.vm.provider :virtualbox do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 1
    end

    gateway.vm.provision "file", source: "clone.sh", destination: "clone.sh"

    gateway.vm.provision :shell, inline: "apt-get update"
    
	gateway.vm.provision "shell", path: "./clone.sh"
	
	gateway.vm.provision :docker
    gateway.vm.provision :docker_compose, yml: "/home/vagrant/lemoras_devops/public_gateway/docker-compose.yml", run:"always", rebuild: true 
  end


end
